### ISSUE TITLE
Problem with token passing

### ISSUE THREAD

**Issue by davidascher** [mozilla/login.webmaker.org#317]
STR:

1. go to https://webmaker-firehose-staging.herokuapp.com/
2. type in da@mozillafoundation.org 
3. get dialog box saying to check email
4. go to email, click on link in email: (https://webmaker-firehose-staging.herokuapp.com//?uid=daa4&token=tabil-jurog&validFor=one-year)
5. get this dialog:

![screenshot 2015-02-05 15 41 16](https://cloud.githubusercontent.com/assets/51278/6071691/8f2bf802-ad4d-11e4-9430-456bc425f984.png)

So a) no way it can be true, as there was a 3 second delay between the two clicks
b) Seems wrong to me that the validity is specified in the query parameters.  I would expect that to be stored serverside and keyed on the token.  Also not sure why we're passing the uid through the query string.

/cc @cadecairos @jbuck @simonwex

**Comment by cadecairos** [comment]
> a) no way it can be true, as there was a 3 second delay between the two clicks

This error masks what really happened, which I believe was mozilla/webmaker-firehose#4


> b) Seems wrong to me that the validity is specified in the query parameters

The validity param actually refers to how long the session cookie should be set for - it tells the browser to ask for a one-year cookie vs a session cookie. Since the cookie generation happens on the app server and not on the login server, it didn't seem necessary to handle that there (on the login server).


> Also not sure why we're passing the uid through the query string.

The instant log in requires knowing the UID (username). Because the log in keys are only 10 characters long, an attacker could theoretically attempt to auth until they hit a valid token for any user, not worrying about also keying the attempt on a uid. Of course, rate limiting also plays a role in mitigating bad things like that.

**Comment by davidascher** [comment]
Cool. I'll follow the other thread. Thanks for the explanation!
